version: "3.9"

networks:
  proxy:
    external: true

services:
  mappatura-backend:
    container_name: mappatura-backend
    volumes:
      - "./db.sqlite:/usr/src/app/db.sqlite"
    networks:
      - proxy
    image: handymenny/mappatura-backend:latest
    init: true
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
